contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.6.33
    packID: CortexAttackSurfaceManagement
    packName: Cortex Attack Surface Management
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook is used to create Jira tickets directed toward service
  owners to notify them of their internet exposures.
id: Cortex ASM - Jira Notification
inputs:
- description: Body of the notification (email or ticket) sent to the potential service
    owner.
  key: OwnerNotificationBody
  playbookInputQuery: null
  required: true
  value: {}
- description: The Jira project key to associate with the issue.
  key: JiraProjectKey
  playbookInputQuery: null
  required: true
  value:
    simple: XPANSE
name: Cortex ASM - Jira Notification
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 18a8542a-f6ca-474e-82bb-cd023bdf2a69
      iscommand: false
      name: ""
      version: -1
    taskid: 18a8542a-f6ca-474e-82bb-cd023bdf2a69
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      IssueTypeID:
        complex:
          accessor: asmattacksurfaceruleid
          root: alert
          transformers:
          - args:
              chars:
                value:
                  simple: '[\"]'
            operator: StripChars
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook pulls remediation guidance off of a list based on
        ASM RuleID to be used in service owner notifications (email or ticketing system).
      id: f25546a1-47be-4b79-803e-013a06424a83
      iscommand: false
      name: Cortex ASM - Remediation Guidance
      playbookId: Cortex ASM - Remediation Guidance
      type: playbook
      version: -1
    taskid: f25546a1-47be-4b79-803e-013a06424a83
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      gridfield:
        simple: asmnotification
      keys:
        simple: type,value,url,timestamp
      val1:
        simple: Jira
      val2:
        complex:
          accessor: Key
          root: Ticket
      val3:
        complex:
          accessor: Key
          root: Ticket
          transformers:
          - operator: FirstArrayElement
          - args:
              prefix:
                value:
                  simple: browse/
              suffix: {}
            operator: concat
          - args:
              prefix:
                iscontext: true
                value:
                  simple: JiraDomain.url
              suffix:
                iscontext: true
            operator: concat
      val4:
        simple: TIMESTAMP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      id: 6e358c93-d64a-421a-8191-780a655d3739
      iscommand: false
      name: Set notification grid field
      script: GridFieldSetup
      type: regular
      version: -1
    taskid: 6e358c93-d64a-421a-8191-780a655d3739
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 530
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e28fdfca-d524-4853-8dc3-285981f0050f
      iscommand: false
      name: Complete
      type: title
      version: -1
    taskid: e28fdfca-d524-4853-8dc3-285981f0050f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 690
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      description:
        complex:
          root: inputs.OwnerNotificationBody
          transformers:
          - args:
              prefix: {}
              suffix:
                iscontext: true
                value:
                  simple: ${RemediationGuidance}
            operator: concat
          - args:
              limit: {}
              replaceWith: {}
              toReplace:
                value:
                  simple: <br>
            operator: replace
      extend-context:
        simple: 'JiraDomain=.={"url": val.self.split(''rest/api'')[0]}'
      issueTypeName:
        simple: Task
      priority:
        complex:
          accessor: severity
          root: alert
          transformers:
          - args:
              input_values:
                value:
                  simple: 1,2,3,4
              mapped_values:
                value:
                  simple: Low,Medium,High,Critical
            operator: MapValuesTransformer
      projectKey:
        complex:
          root: inputs.JiraProjectKey
      summary:
        complex:
          accessor: name
          root: alert
          transformers:
          - args:
              prefix:
                value:
                  simple: 'Cortex ASM Alert: '
              suffix: {}
            operator: concat
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Creates a new issue in Jira.
      id: 7c511059-67eb-4f35-82ca-a27f2b2ad513
      iscommand: true
      name: Create Jira ticket
      script: '|||jira-create-issue'
      type: regular
      version: -1
    taskid: 7c511059-67eb-4f35-82ca-a27f2b2ad513
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 705,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
