contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.7.30
    packID: CortexAttackSurfaceManagement
    packName: Cortex Attack Surface Management
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook adds new block rule(s) to on-prem firewall vendors in order to block internet access for internet exposures.

  Conditions:
  - Multiple integration instances configured at the same time are not supported (Panorama or standalone NGFW).
  - Multiple rules with the same name in different device-groups not supported (Panorama).
  - !pan-os-list-services will fail if there are no services in a specific device-group (Panorama).
id: Cortex ASM - On Prem Remediation
inputs:
- description: Firewall rule name to look up in the company configuration setting
    for block rule.
  key: RuleName
  playbookInputQuery: null
  required: true
  value: {}
- description: IP address of the service.
  key: RemoteIP
  playbookInputQuery: null
  required: true
  value:
    complex:
      accessor: remoteip
      root: alert
- description: Protocol of the service.
  key: RemoteProtocol
  playbookInputQuery: null
  required: true
  value:
    complex:
      accessor: appid
      root: alert
- description: Port number of the service.
  key: RemotePort
  playbookInputQuery: null
  required: true
  value:
    complex:
      accessor: remoteport
      root: alert
- description: Device group of the firewall rule to lookup.
  key: DeviceGroup
  playbookInputQuery: null
  required: false
  value: {}
- description: If the rule, address and service are created in the "Shared" location,
    we need to know what device groups we can push to because it isn't possible to
    push to the "Shared" location.
  key: SecondaryDeviceGroup
  playbookInputQuery: null
  required: false
  value: {}
name: Cortex ASM - On Prem Remediation
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 573237c6-7130-41ce-8653-2294f0b6ac94
      iscommand: false
      name: ""
      version: -1
    taskid: 573237c6-7130-41ce-8653-2294f0b6ac94
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 460,
          "y": -460
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      rulename:
        complex:
          root: inputs.RuleName
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Returns a list of predefined Security Rules. (When passing a query,
        all other arguments are overridden. Make sure the query includes all the filters
        you want).
      id: 22c135e5-6fc0-4464-87da-f8c0ae25220b
      iscommand: true
      name: pan-os-list-rules
      script: Panorama|||pan-os-list-rules
      type: regular
      version: -1
    taskid: 22c135e5-6fc0-4464-87da-f8c0ae25220b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": -140
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      AutoCommit:
        simple: "True"
      DestinationZone:
        complex:
          accessor: To
          root: Panorama.SecurityRule
      DeviceGroup:
        complex:
          root: inputs.DeviceGroup
      IP:
        complex:
          root: inputs.RemoteIP
      LogForwarding:
        complex:
          accessor: LogForwardingProfile
          root: Panorama.SecurityRule
      ObjectNamePrefix:
        simple: xpanse-ar-object-
      Port:
        complex:
          root: inputs.RemotePort
          transformers:
          - operator: Stringify
      Protocol:
        complex:
          root: inputs.RemoteProtocol
      RuleNamePrefix:
        simple: xpanse-ar-rule
      SecondaryDeviceGroup:
        complex:
          root: inputs.SecondaryDeviceGroup
      ServiceNamePrefix:
        simple: xpanse-ar-service-
      SourceZone:
        complex:
          accessor: From
          root: Panorama.SecurityRule
      WhereRule:
        simple: top
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: 'This playbook blocks a destination IP and service (TCP or UDP
        port) by creating a rule for a specific device group on PAN-OS. '
      id: 6db7e419-5848-487b-8eba-03db46a125bc
      iscommand: false
      name: PAN-OS - Block Destination Service
      playbookName: PAN-OS - Block Destination Service
      type: playbook
      version: -1
    taskid: 6db7e419-5848-487b-8eba-03db46a125bc
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 460,
          "y": 400
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d74fd530-00ae-4377-8dbf-8681f4a7a605
      iscommand: false
      name: Complete
      type: title
      version: -1
    taskid: d74fd530-00ae-4377-8dbf-8681f4a7a605
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 460,
          "y": 590
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.DeviceGroup
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "1"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if DeviceGroup input is specified because of different !pan-os-list-rule
        commands for standalone firewall vs Panorama.
      id: 58615c42-a7f4-4159-8412-b7095c9854c0
      iscommand: false
      name: Is DeviceGroup specified?
      type: condition
      version: -1
    taskid: 58615c42-a7f4-4159-8412-b7095c9854c0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 460,
          "y": -340
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      device-group:
        complex:
          root: inputs.DeviceGroup
      pre_post:
        simple: pre-rulebase
      rulename:
        complex:
          root: inputs.RuleName
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Returns a list of predefined security rules. (When passing a query,
        all other arguments are overridden. Make sure the query includes all the filters
        you want).
      id: 54b86def-75f3-4fe8-8779-4fbec1d42728
      iscommand: true
      name: pan-os-list-rules (pre-rulebase)
      script: Panorama|||pan-os-list-rules
      type: regular
      version: -1
    taskid: 54b86def-75f3-4fe8-8779-4fbec1d42728
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 890,
          "y": -140
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      device-group:
        complex:
          root: inputs.DeviceGroup
      pre_post:
        simple: post-rulebase
      rulename:
        complex:
          root: inputs.RuleName
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Returns a list of predefined security rules. (When passing a query,
        all other arguments are overridden. Make sure the query includes all the filters
        you want).
      id: a918e4e4-2ea8-4d70-883d-5265ce5be25d
      iscommand: true
      name: pan-os-list-rules (post-rulebase)
      script: Panorama|||pan-os-list-rules
      type: regular
      version: -1
    taskid: a918e4e4-2ea8-4d70-883d-5265ce5be25d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 890,
          "y": 20
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Name
                root: Panorama.SecurityRule
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if firewall rule information was found.
      id: c9013687-cd7c-4bf3-8c8b-89c45aa03d07
      iscommand: false
      name: Was rule information found?
      type: condition
      version: -1
    taskid: c9013687-cd7c-4bf3-8c8b-89c45aa03d07
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 460,
          "y": 190
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 810,
        "x": 460,
        "y": -460
      }
    }
  }
