contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    itemVersion: 3.0.21
    packID: Core
    packName: Core - Investigation and Response
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
deprecated: true
description: "Deprecated. Use `Cloud IAM User Access Investigation` instead. Respond
  to Cortex XDR Cloud alerts where an AWS IAM user`s access key is used suspiciously
  to access the cloud environment. \nThe following alerts are supported for AWS environments.\n-
  Penetration testing tool attempt\n- Penetration testing tool activity\n- Suspicious
  API call from a Tor exit node\n This is a beta playbook, which lets you implement
  and test pre-release software. Although AWS is supported, we are working towards
  multi-cloud support. As the playbook is beta, it might contain bugs. Updates to
  the playbook during the beta phase might include non-backward compatible features.
  We encourage your feedback on the quality and usability of the content to help us
  identify and fix issues, so we can continually improve the content.\n"
id: AWS IAM User Access Investigation - Remediation
inputs:
- description: The name of the user whose key you want to update.
  key: userName
  playbookInputQuery: null
  required: false
  value: {}
- description: The access key ID of the secret access key you want to update.
  key: accessKeyId
  playbookInputQuery: null
  required: false
  value: {}
- description: Whether to automatically delete the user login profile, if it exists
    (True/False).
  key: AutoDeleteProfile
  playbookInputQuery: null
  required: false
  value: {}
- description: The IP address to block using the playbook.
  key: IP
  playbookInputQuery: null
  required: false
  value: {}
- description: Whether to initiate the block IP playbook automatically (True/False).
  key: AutoBlockIP
  playbookInputQuery: null
  required: false
  value:
    simple: "False"
- description: |-
    The Tag name for bad reputation IP addresses investigated in the incident.
    Use it when the EDL service is configured to add indicators to block in PANW PAN-OS.
    If indicator verdict (Malicious/Bad) is used to add indicators to Cortex XSIAM EDL, you don't need to use the tag. Indicators are set as malicious, automatically in the incident.
  key: IndicatorTag
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Determines whether Palo Alto Networks Panorama or Firewall Dynamic Address Groups are used.
    Specify the Dynamic Address Group tag name for IP handling.
  key: DAG
  playbookInputQuery: null
  required: false
  value: {}
name: AWS IAM User Access Investigation - Remediation
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "43"
      - "44"
      - "45"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 84f6f072-180e-47db-8fe0-ee5bb5acdd41
      iscommand: false
      name: ""
      version: -1
    taskid: 84f6f072-180e-47db-8fe0-ee5bb5acdd41
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 230,
          "y": 1830
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      accessKeyId:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.accessKeyId
              operator: startWith
              right:
                value:
                  simple: AKIA
          root: inputs.accessKeyId
          transformers:
          - operator: uniq
      status:
        simple: Inactive
      userName:
        complex:
          accessor: UserName
          root: AWS.IAM.Users.AccessKeys
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Changes the status of the specified access key from Active to Inactive,
        or vice versa. This operation can be used to disable a user's key as part
        of a key rotation workflow.
      id: a8aef032-bec2-424e-8bfc-bc21ca561c73
      iscommand: true
      name: Set compromised IAM access key as inactive
      script: '|||aws-iam-update-access-key'
      type: regular
      version: -1
    taskid: a8aef032-bec2-424e-8bfc-bc21ca561c73
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 230,
          "y": 2120
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      userName:
        complex:
          root: inputs.userName
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Deletes the password for the specified IAM user, which terminates
        the user's ability to access AWS services through the AWS Management Console.
      id: 30e0980e-0afa-4f55-8975-5ed40cdf922a
      iscommand: true
      name: Delete user login profile to AWS console
      script: '|||aws-iam-delete-login-profile'
      type: regular
      version: -1
    taskid: 30e0980e-0afa-4f55-8975-5ed40cdf922a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -640,
          "y": 2625
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: name
                root: alert
          operator: containsGeneral
          right:
            value:
              simple: Suspicious API call from a Tor exit node
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "37"
      - "38"
      "yes":
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Is it a Tor IP?
      id: 74f4159d-9adc-4f86-8c48-e225a0594549
      iscommand: false
      name: Is it a Tor IP?
      type: condition
      version: -1
    taskid: 74f4159d-9adc-4f86-8c48-e225a0594549
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 900,
          "y": 2120
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9fa21b96-265c-49ac-893d-8b0e6b9dba62
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 9fa21b96-265c-49ac-893d-8b0e6b9dba62
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 230,
          "y": 2800
        }
      }
  "29":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: AWS.IAM.Users.LoginProfile
          operator: isNotEmpty
      label: Delete profile
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "19"
      Delete profile:
      - "47"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Check the user AWS login profile configuration.\nIf a login profile
        is configured, it needs to be deleted. \n\nThe user login profile configuration
        can be found under https://console.aws.amazon.com/iam/home#/users/[username]
        under the security credentials tab."
      id: 5a2c2e61-0d88-498f-8dad-13e34ec2fdf9
      iscommand: false
      name: Check for AWS user login profile
      type: condition
      version: -1
    taskid: 5a2c2e61-0d88-498f-8dad-13e34ec2fdf9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -450,
          "y": 2275
        }
      }
  "37":
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      indicatorsValues:
        complex:
          root: inputs.IP
      tags:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.IndicatorTag
              operator: isNotEmpty
          root: inputs.IndicatorTag
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.indicators
      id: beaa19aa-4406-4952-894b-692cd748f995
      iscommand: true
      name: 'Tag indicators for EDL '
      script: Builtin|||setIndicators
      type: regular
      version: -1
    taskid: beaa19aa-4406-4952-894b-692cd748f995
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1140,
          "y": 2295
        }
      }
  "38":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.AutoBlockIP
                transformers:
                - operator: toLowerCase
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "38"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "39"
      "yes":
      - "49"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ''''''
      id: d59025a2-7aae-4025-8767-5789cd562b9c
      iscommand: false
      name: Automatically block IP?
      type: condition
      version: -1
    taskid: d59025a2-7aae-4025-8767-5789cd562b9c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1570,
          "y": 2295
        }
      }
  "39":
    continueonerrortype: ""
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Block IP address according to IP enrichment and reputation results.
      id: e9376eaa-766f-4fe9-8601-4a9c0b0ab6fd
      iscommand: false
      name: 'Manual - Block IP '
      type: regular
      version: -1
    taskid: e9376eaa-766f-4fe9-8601-4a9c0b0ab6fd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1790,
          "y": 2470
        }
      }
  "43":
    continueonerrortype: ""
    id: "43"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3d72057b-f65c-4e75-872d-d54e076c97af
      iscommand: false
      name: Set compromised IAM access key as inactive
      type: title
      version: -1
    taskid: 3d72057b-f65c-4e75-872d-d54e076c97af
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 230,
          "y": 1970
        }
      }
  "44":
    continueonerrortype: ""
    id: "44"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "46"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8beeeaf8-6a1c-45f9-8f8f-27cca7e19cb5
      iscommand: false
      name: Handle user login profile
      type: title
      version: -1
    taskid: 8beeeaf8-6a1c-45f9-8f8f-27cca7e19cb5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -450,
          "y": 1970
        }
      }
  "45":
    continueonerrortype: ""
    id: "45"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d811738c-257e-4e67-80cf-3e5460868279
      iscommand: false
      name: Handle Tor IP
      type: title
      version: -1
    taskid: d811738c-257e-4e67-80cf-3e5460868279
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1970
        }
      }
  "46":
    continueonerrortype: ""
    id: "46"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "29"
    note: false
    quietmode: 0
    scriptarguments:
      userName:
        complex:
          root: inputs.userName
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Retrieves the user login profile information for AWS management
        console.
      id: 5443f14c-a792-4c17-80f0-fcaa0fd5318e
      iscommand: true
      name: AWS IAM - Get user profile
      script: '|||aws-iam-get-user-login-profile'
      type: regular
      version: -1
    taskid: 5443f14c-a792-4c17-80f0-fcaa0fd5318e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -450,
          "y": 2120
        }
      }
  "47":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.AutoDeleteProfile
                transformers:
                - operator: toLowerCase
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "47"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "48"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Whether to automatically delete a user login profile.
      id: 8a94ae35-9772-4ab3-889a-b7e026c9ca3b
      iscommand: false
      name: Automatically delete user login profile?
      type: condition
      version: -1
    taskid: 8a94ae35-9772-4ab3-889a-b7e026c9ca3b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -870,
          "y": 2450
        }
      }
  "48":
    continueonerrortype: ""
    id: "48"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Manually delete a user login profile.
      id: a7d78a6c-2ab2-4484-8c8d-7ae2caf9146b
      iscommand: false
      name: Delete user login profile - Manual
      type: regular
      version: -1
    taskid: a7d78a6c-2ab2-4484-8c8d-7ae2caf9146b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -1110,
          "y": 2625
        }
      }
  "49":
    continueonerrortype: ""
    id: "49"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      AutoCommit:
        simple: "No"
      CustomBlockRule:
        simple: "True"
      IP:
        complex:
          root: inputs.IP
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |+
        This playbook blocks malicious indicators using all integrations that are enabled, using the following sub-playbooks:

        - Block URL - Generic
        - Block Account - Generic
        - Block IP - Generic v2
        - Block File - Generic v2
        - Block Email - Generic
        - Block Domain - Generic

      id: 5fa155b5-8ecc-44c1-8dd2-f41ee7263a08
      iscommand: false
      name: Block Indicators - Generic v2
      playbookId: Block Indicators - Generic v2
      type: playbook
      version: -1
    taskid: 5fa155b5-8ecc-44c1-8dd2-f41ee7263a08
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 2470
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "17_19_yes": 0.1,
      "17_37_#default#": 0.43,
      "17_38_#default#": 0.61,
      "38_39_#default#": 0.52
    },
    "paper": {
      "dimensions": {
        "height": 1035,
        "width": 3280,
        "x": -1110,
        "y": 1830
      }
    }
  }
