contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    itemVersion: 3.0.20
    packID: Core
    packName: Core - Investigation and Response
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
deprecated: true
description: "Deprecated. Use `Cloud IAM User Access Investigation` instead. Investigate
  and respond to Cortex XSIAM alerts where an AWS IAM user`s access key is used suspiciously
  to access the cloud environment. \nThe following alerts are supported for AWS environments.\n-
  Penetration testing tool attempt\n- Penetration testing tool activity\n- Suspicious
  API call from a Tor exit node\n This is a beta playbook, which lets you implement
  and test pre-release software. Although AWS is supported, we are working towards
  multi-cloud support. As the playbook is beta, it might contain bugs. Updates to
  the playbook during the beta phase might include non-backward compatible features.
  We encourage feedback on the quality and usability of the content to help us identify
  and fix issues, so we can continually improve the content.\n"
id: AWS IAM User Access Investigation
inputs:
- description: Whether to automatically delete the user login profile if it exists
    (True/False).
  key: AutoDeleteProfile
  playbookInputQuery: null
  required: false
  value:
    simple: "False"
- description: 'Whether to initiate block IP playbook automatically (True/False). '
  key: AutoBlockIP
  playbookInputQuery: null
  required: false
  value:
    simple: "False"
- description: |-
    The tag name for bad reputation IP addresses investigated in the incident.
    Use this when the EDL service is configured to add indicators to block in PANW PAN-OS.
    If the indicator verdict (Malicious/Bad) is used to add indicators to Cortex XSIAM EDL you don't need to use the tag. Indicators are set as malicious, automatically in the incident.
  key: IndicatorTag
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    This input determines whether Palo Alto Networks Panorama or Firewall Dynamic Address Groups are used.
    Specify the Dynamic Address Group tag name for IP handling.
  key: DAG
  playbookInputQuery: null
  required: false
  value: {}
- description: Whether to close alerts automatically as a false positive (True/False).
  key: ShouldCloseAutomatically
  playbookInputQuery: null
  required: false
  value: {}
name: AWS IAM User Access Investigation
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "48"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 40b4c735-392d-4c86-8ab3-6d49441a813d
      iscommand: false
      name: ""
      version: -1
    taskid: 40b4c735-392d-4c86-8ab3-6d49441a813d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 550,
          "y": -70
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "54"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c48a2862-f3e1-4dd3-89b7-8590f645298b
      iscommand: false
      name: 'Remediation '
      type: title
      version: -1
    taskid: c48a2862-f3e1-4dd3-89b7-8590f645298b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 550,
          "y": 1090
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1e498a1e-df55-4805-8fa9-973ba6554ac1
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 1e498a1e-df55-4805-8fa9-973ba6554ac1
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 510,
          "y": 1750
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      False Positive:
      - "64"
      True positive:
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Based on the collected data investigation and the verdict established
        by the "Enrichment for Verdict" playbook, is this a true positive event?
      id: f452a1bf-3fc3-40db-8d4a-1666372f6a82
      iscommand: false
      name: Manual decision making - true/false-positive alert
      type: condition
      version: -1
    taskid: f452a1bf-3fc3-40db-8d4a-1666372f6a82
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 220,
          "y": 920
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 043b96c8-7870-4754-823d-3a0658690cf2
      iscommand: false
      name: False Positive - Done
      type: title
      version: -1
    taskid: 043b96c8-7870-4754-823d-3a0658690cf2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -90,
          "y": 1610
        }
      }
  "48":
    continueonerrortype: ""
    id: "48"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "61"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 99d6201c-337d-4da6-82a1-bcd06c48573b
      iscommand: false
      name: Enrichment
      type: title
      version: -1
    taskid: 99d6201c-337d-4da6-82a1-bcd06c48573b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 550,
          "y": 80
        }
      }
  "50":
    continueonerrortype: ""
    id: "50"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "66"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cee3b559-fdae-4404-863c-39f9dd375566
      iscommand: false
      name: Verdict
      type: title
      version: -1
    taskid: cee3b559-fdae-4404-863c-39f9dd375566
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 550,
          "y": 600
        }
      }
  "54":
    continueonerrortype: ""
    id: "54"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "57"
    note: false
    quietmode: 0
    scriptarguments:
      AutoBlockIP:
        complex:
          root: inputs.AutoBlockIP
      AutoDeleteProfile:
        complex:
          root: inputs.AutoDeleteProfile
      DAG:
        complex:
          root: inputs.DAG
      IP:
        complex:
          accessor: hostip
          root: alert
      IndicatorTag:
        complex:
          root: inputs.IndicatorTag
      accessKeyId:
        complex:
          accessor: accessKeyId
          root: Core.OriginalAlert.event.identity_orig
      userName:
        complex:
          accessor: username
          root: alert
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: "Investigate and respond to Cortex XSIAM alerts where an AWS IAM
        user`s access key is used suspiciously to access the cloud environment. \nThe
        following alerts are supported for AWS environments.\n- Penetration testing
        tool attempt\n- Penetration testing tool activity\n- Suspicious API call from
        a Tor exit node\n This is a beta playbook, which lets you implement and test
        pre-release software. Although AWS is supported, we are working towards multi-cloud
        support. As the playbook is beta, it might contain bugs. Updates to the playbook
        during the beta phase might include non-backward compatible features. We encourage
        feedback on the quality and usability of the content to help us identify and
        fix issues, sp we can continually improve content.\n"
      id: 65900bdd-a39d-4848-8edc-4a3026a5360c
      iscommand: false
      name: AWS IAM User Access Investigation - Remediation
      playbookId: AWS IAM User Access Investigation - Remediation
      type: playbook
      version: -1
    taskid: 65900bdd-a39d-4848-8edc-4a3026a5360c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 550,
          "y": 1240
        }
      }
  "57":
    continueonerrortype: ""
    id: "57"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "65"
      "yes":
      - "58"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Close the alert and finish the investigation?
      id: 9bc32470-1e47-447a-8a0b-f41a4049394c
      iscommand: false
      name: Close the alert and finish the investigation?
      type: condition
      version: -1
    taskid: 9bc32470-1e47-447a-8a0b-f41a4049394c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 550,
          "y": 1410
        }
      }
  "58":
    continueonerrortype: ""
    id: "58"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 2c77b9cd-84ff-48cc-86cd-a3cb3f439314
      iscommand: true
      name: Close alert after remediation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 2c77b9cd-84ff-48cc-86cd-a3cb3f439314
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 780,
          "y": 1580
        }
      }
  "60":
    continueonerrortype: ""
    id: "60"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "50"
    note: false
    quietmode: 0
    scriptarguments:
      CloseReason:
        simple: Resolved - False Positive,Resolved - Duplicate Incident,Resolved -
          Known Issue
      Domain:
        complex:
          accessor: domainname
          root: alert
      FileSHA256:
        complex:
          accessor: initiatorsha256
          root: alert
      IP:
        complex:
          accessor: hostip
          root: alert
      URL:
        complex:
          accessor: url
          root: alert
      User:
        complex:
          accessor: username
          root: alert
      awsUser:
        complex:
          accessor: username
          root: alert
      query:
        simple: (hostip:${alert.hostip}) and alertsource:${alert.sourceBrand} and
          alertname:${alert.name}
      threshold:
        simple: "5"
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook checks prior alert closing reasons and performs enrichment
        and prevalence checks on different IOC types. It then returns the information
        needed to establish the alert's verdict.
      id: fe3f84ca-6874-4450-85d7-4de28a71fd11
      iscommand: false
      name: Enrichment for Verdict
      playbookId: Enrichment for Verdict
      type: playbook
      version: -1
    taskid: fe3f84ca-6874-4450-85d7-4de28a71fd11
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 550,
          "y": 420
        }
      }
  "61":
    continueonerrortype: ""
    id: "61"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "60"
    note: false
    quietmode: 0
    scriptarguments:
      alert_ids:
        complex:
          accessor: id
          root: alert
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns information about each alert ID.
      id: 6c5bcd44-dde7-429a-8838-d0e78c895537
      iscommand: true
      name: Get cloud original alert
      script: '|||core-get-cloud-original-alerts'
      type: regular
      version: -1
    taskid: 6c5bcd44-dde7-429a-8838-d0e78c895537
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 550,
          "y": 220
        }
      }
  "64":
    continueonerrortype: ""
    id: "64"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      ShouldCloseAutomatically:
        complex:
          root: inputs.ShouldCloseAutomatically
      alertName:
        complex:
          accessor: name
          root: alert
      sourceIP:
        complex:
          accessor: hostip
          root: alert
      username:
        complex:
          accessor: username
          root: alert
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |
        This playbook handles false positive alerts.
      id: 8eded0e7-c70b-40a6-8515-6a3215682533
      iscommand: false
      name: Handle False Positive Alerts
      playbookId: Handle False Positive Alerts
      type: playbook
      version: -1
    taskid: 8eded0e7-c70b-40a6-8515-6a3215682533
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -90,
          "y": 1090
        }
      }
  "65":
    continueonerrortype: ""
    id: "65"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Continue the investigation.
      id: 62cfaa81-81fb-4166-8f73-e3e903c5e3c5
      iscommand: false
      name: Continue the investigation
      type: regular
      version: -1
    taskid: 62cfaa81-81fb-4166-8f73-e3e903c5e3c5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 320,
          "y": 1580
        }
      }
  "66":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: alert.name
          operator: containsGeneral
          right:
            value:
              simple: Suspicious API call from a Tor exit node
        - left:
            iscontext: true
            value:
              simple: IPVerdict
          operator: isEqualString
          right:
            value:
              simple: Suspicious
      label: "yes"
    continueonerrortype: ""
    id: "66"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "21"
      "yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Is it a suspicious or Tor IP?
      id: ac7a9b9c-0d3c-494a-8def-9884ca58aadf
      iscommand: false
      name: Is it a suspicious or Tor IP?
      type: condition
      version: -1
    taskid: ac7a9b9c-0d3c-494a-8def-9884ca58aadf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 550,
          "y": 750
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "21_64_False Positive": 0.54,
      "21_8_True positive": 0.48,
      "57_58_yes": 0.82,
      "66_8_yes": 0.37
    },
    "paper": {
      "dimensions": {
        "height": 1885,
        "width": 1250,
        "x": -90,
        "y": -70
      }
    }
  }
