contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: a3cf2c24-dd12-449d-8c9d-dc0a35bb8ee0
inputs: []
name: asdasd
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4daf2a39-3056-4458-8da2-323a47e086be
      iscommand: false
      name: ""
      version: -1
    taskid: 4daf2a39-3056-4458-8da2-323a47e086be
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3b3494ea-2063-4c44-8c9f-758ba83d5fbc
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 3b3494ea-2063-4c44-8c9f-758ba83d5fbc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 480
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 525,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
