contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: aef6caef-e656-423d-819d-2157e65c9e50
inputs: []
name: temp
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 54220d21-ce3d-4a81-8e34-e8c336917fd2
      iscommand: false
      name: ""
      version: -1
    taskid: 54220d21-ce3d-4a81-8e34-e8c336917fd2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 37e76782-4f5e-4863-8895-e9dd3f07c480
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 37e76782-4f5e-4863-8895-e9dd3f07c480
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 260
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 305,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
