contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 1.6.33
    packID: CortexAttackSurfaceManagement
    packName: Cortex Attack Surface Management
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
deprecated: true
description: Deprecated. No available replacement. This playbook will look up an IP
  address in Tenable.io or Rapid7 InsightVM.
id: Cortex ASM - Vulnerability Management Enrichment
inputs:
- description: IP address to look up in VM tool
  key: IP
  playbookInputQuery: null
  required: true
  value: {}
- description: How many days in the past to look for scan results
  key: DaysPast
  playbookInputQuery: null
  required: false
  value:
    simple: "30"
- description: The Tenable.io Scan Template ID used to launch a new scan
  key: TenableScanId
  playbookInputQuery: null
  required: false
  value: {}
name: Cortex ASM - Vulnerability Management Enrichment
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 99e75dec-0004-47a8-86cf-7784768b7eda
      iscommand: false
      name: ""
      version: -1
    taskid: 99e75dec-0004-47a8-86cf-7784768b7eda
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 340,
          "y": -80
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: true
    quietmode: 0
    scriptarguments:
      dateRange:
        complex:
          root: inputs.DaysPast
      ip:
        complex:
          root: inputs.IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Tenable.io
      description: Gets a list of up to 5000 of the vulnerabilities recorded for a
        specified asset.
      id: 1b0ec0f3-2081-4b8b-881e-d99c2266923a
      iscommand: true
      name: tenable-io-get-vulnerabilities-by-asset
      script: Tenable.io|||tenable-io-get-vulnerabilities-by-asset
      type: regular
      version: -1
    taskid: 1b0ec0f3-2081-4b8b-881e-d99c2266923a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -380,
          "y": 660
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Tenable.io
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 62582fbd-65c0-47b3-8bbb-1a9561dfe459
      iscommand: false
      name: Is Tenable.io Enabled?
      type: condition
      version: -1
    taskid: 62582fbd-65c0-47b3-8bbb-1a9561dfe459
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 280
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 53703990-ba87-45dc-8f65-5d69f77498be
      iscommand: false
      name: Complete
      type: title
      version: -1
    taskid: 53703990-ba87-45dc-8f65-5d69f77498be
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 340,
          "y": 1700
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "9"
      "yes":
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: TenableIO.Vulnerabilities
              operator: isNotEmpty
          root: TenableIO.Vulnerabilities
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 33292a48-5944-46a2-8e6b-b738b713588d
      iscommand: false
      name: Do Vulnerability Findings Exist?
      script: Exists
      type: condition
      version: -1
    taskid: 33292a48-5944-46a2-8e6b-b738b713588d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -380,
          "y": 870
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6468186e-8384-435f-81a7-24e2a0f11e1b
      iscommand: false
      name: Launch Vulnerability Assessment scan manually in https://cloud.tenable.com/
      type: regular
      version: -1
    taskid: 6468186e-8384-435f-81a7-24e2a0f11e1b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -380,
          "y": 1310
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          root: inputs.IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 43905bfc-f344-4ca4-8f3d-1419a7eee40f
      iscommand: false
      name: IP address exists?
      script: Exists
      type: condition
      version: -1
    taskid: 43905bfc-f344-4ca4-8f3d-1419a7eee40f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -380,
          "y": 460
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      scanId:
        complex:
          root: inputs.TenableScanId
      scanTargets:
        complex:
          root: inputs.IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Tenable.io
      description: Launches a scan with existing or custom targets. You can specify
        custom targets in the command arguments.
      id: 40bc4d00-f2f0-4f09-846e-4bb6d741f4fa
      iscommand: true
      name: tenable-io-launch-scan
      script: Tenable.io|||tenable-io-launch-scan
      type: regular
      version: -1
    taskid: 40bc4d00-f2f0-4f09-846e-4bb6d741f4fa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -870,
          "y": 1310
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "6"
      "yes":
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          root: inputs.TenableScanId
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 4f356cc5-aad3-4598-8579-8daef5c87471
      iscommand: false
      name: Does Tenable.io Scan ID Exist?
      script: Exists
      type: condition
      version: -1
    taskid: 4f356cc5-aad3-4598-8579-8daef5c87471
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -380,
          "y": 1100
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Rapid7 Nexpose
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 449c2e79-6a4b-46d8-8dc2-f5e5522eee4e
      iscommand: false
      name: Is Rapid7 InsightVM Enabled?
      type: condition
      version: -1
    taskid: 449c2e79-6a4b-46d8-8dc2-f5e5522eee4e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 630,
          "y": 280
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          root: inputs.IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 3723ac9c-1631-46ad-8297-35db74e7e696
      iscommand: false
      name: IP address exists?
      script: Exists
      type: condition
      version: -1
    taskid: 3723ac9c-1631-46ad-8297-35db74e7e696
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 950,
          "y": 460
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      ipAddressIs:
        complex:
          root: inputs.IP
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Returns all assets for which you have access that match the given
        search criteria.
      id: 38292c41-5da6-487b-8f00-5a002749db80
      iscommand: true
      name: nexpose-search-assets
      script: '|||nexpose-search-assets'
      type: regular
      version: -1
    taskid: 38292c41-5da6-487b-8f00-5a002749db80
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 950,
          "y": 660
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "14"
      "yes":
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: Assessed
          root: Nexpose.Asset
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 0ac02fa0-760b-4a95-8e9f-733128e064f6
      iscommand: false
      name: Has Asset been assessed by Rapid7
      script: Exists
      type: condition
      version: -1
    taskid: 0ac02fa0-760b-4a95-8e9f-733128e064f6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 950,
          "y": 870
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      IPs:
        complex:
          root: inputs.IP
      name:
        complex:
          root: inputs.IP
          transformers:
          - args:
              prefix:
                value:
                  simple: 'VM Scan of '
              suffix:
                value:
                  simple: ' started by Cortex XSIAM'
            operator: concat
    separatecontext: false
    skipunavailable: true
    task:
      brand: Rapid7 Nexpose
      description: Starts a scan for specified asset IP addresses and host names.
      id: 1a50b035-c5a8-477d-8ab2-2c0b60834377
      iscommand: true
      name: nexpose-start-assets-scan
      script: Rapid7 Nexpose|||nexpose-start-assets-scan
      type: regular
      version: -1
    taskid: 1a50b035-c5a8-477d-8ab2-2c0b60834377
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1490,
          "y": 1110
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: true
    quietmode: 0
    scriptarguments:
      columns:
        simple: AssetId,Name,Assessed,LastScanId, Vulnerabilities
      data:
        complex:
          accessor: Assets
          root: Nexpose
      title:
        complex:
          accessor: AssetId
          root: Nexpose.Asset
          transformers:
          - args:
              prefix:
                value:
                  simple: 'Results for asset - '
              suffix: {}
            operator: concat
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Convert an array to a nice table display. Usually, from the context.
      id: 3e07f752-bc7d-451c-84b7-135af8747312
      iscommand: false
      name: Print Asset Results
      script: ToTable
      type: regular
      version: -1
    taskid: 3e07f752-bc7d-451c-84b7-135af8747312
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 950,
          "y": 1110
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1845,
        "width": 2740,
        "x": -870,
        "y": -80
      }
    }
  }
