contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    itemVersion: 2.0.12
    packID: Core
    packName: Core - Investigation and Response
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook get as an input all of the involved IP addresses and identities from the Impossible Traveler playbook alert, and enriches them based on the following:
  * Geo location
  * Active Directory
  * IP enrichment e.g. VirusTotal, AbuseIPDB, etc.
id: Impossible Traveler - Enrichment
inputs:
- description: The source IP to iterate over.
  key: sourceip
  playbookInputQuery: null
  required: false
  value: {}
- description: The username to iterate over.
  key: username
  playbookInputQuery: null
  required: false
  value: {}
- description: The organization domain.
  key: domain
  playbookInputQuery: null
  required: false
  value: {}
name: Impossible Traveler - Enrichment
outputs:
- contextPath: ActiveDirectory.Users.manager
  description: The manager of the user.
- contextPath: IP
  description: The IP enrichment results.
  type: unknown
- contextPath: IP.Geo
  description: The IP geo information.
  type: unknown
- contextPath: IP.Malicious
  description: The IP verdict.
  type: unknown
- contextPath: AbuseIPDB.IP
  description: The IP information retrieved from AbuseIPDB.
  type: unknown
- contextPath: AbuseIPDB.IP.Geo
  description: The IP geo information.
  type: unknown
- contextPath: DBotScore
  description: The DBotScore
  type: unknown
- contextPath: AbuseIPDB.IP.Malicious
  description: The IP verdict.
  type: unknown
- contextPath: Account
  description: The account object.
  type: unknown
- contextPath: ActiveDirectory.Users
  description: The AD users.
  type: unknown
- contextPath: MSGraphUser
  description: The user information retrieved from MSGraphUser
  type: unknown
- contextPath: MSGraphUserManager.Manager
  description: The user's manager information retrieved from MSGraphUser.
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7ccb9fd5-4d10-49ab-89c8-a920b9547981
      iscommand: false
      name: ""
      version: -1
    taskid: 7ccb9fd5-4d10-49ab-89c8-a920b9547981
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -865
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.username
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "27"
      "yes":
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether there is a username for the offending user in context,
        and whether Active Directory v2 is enabled.
      id: 26e7340f-7890-4435-8c78-04ad7fcbafca
      iscommand: false
      name: Is there account to be enriched?
      type: condition
      version: -1
    taskid: 26e7340f-7890-4435-8c78-04ad7fcbafca
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 110
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f38df01f-6b55-466a-8bce-2e98b9b287d0
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f38df01f-6b55-466a-8bce-2e98b9b287d0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 940
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      method:
        simple: GET
      url:
        simple: http://www.geoplugin.net/json.gp?ip=${inputs.sourceip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends an HTTP request. Returns the response as Json.
      id: 8f0bc025-3ee1-42b3-8f04-524a31b916df
      iscommand: false
      name: Get coordinates for the IP Addresses
      script: http
      type: regular
      version: -1
    taskid: 8f0bc025-3ee1-42b3-8f04-524a31b916df
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -570
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
      - "16"
      - "19"
      - "24"
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: Coordinates=
      ignore-outputs:
        simple: "true"
      value:
        complex:
          accessor: Body
          root: HttpRequest.Response
          transformers:
          - operator: Stringify
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Parse a given JSON string "value" to a representative object.
        For example: ''{"a": "value"}'' => {"a": "value"}.'
      id: eb064458-d034-4248-89a9-3fac30ef7520
      iscommand: false
      name: Parse HTTP response JSON
      script: ParseJSON
      type: regular
      version: -1
    taskid: eb064458-d034-4248-89a9-3fac30ef7520
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -410
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Events.location
      value:
        complex:
          accessor: geoplugin_latitude
          root: Coordinates
          transformers:
          - args:
              item:
                iscontext: true
                value:
                  simple: Coordinates.geoplugin_longitude
            operator: append
          - args:
              separator:
                value:
                  simple: ', '
            operator: join
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value in context under the key you entered.
      id: f03e3aee-72d7-456e-8c29-48df8ffadc9b
      iscommand: false
      name: Set Location
      script: Set
      type: regular
      version: -1
    taskid: f03e3aee-72d7-456e-8c29-48df8ffadc9b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": -230
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Events.event_timestamp
      value:
        complex:
          accessor: created
          root: alert
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value in context under the key you entered.
      id: 31b0887a-17b7-4446-8ae3-9286cb07a564
      iscommand: false
      name: Set Event Time
      script: Set
      type: regular
      version: -1
    taskid: 31b0887a-17b7-4446-8ae3-9286cb07a564
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -340,
          "y": -230
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: HttpRequest.Response
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 8ae6b224-d274-49e6-8665-43b78bdd5b6d
      iscommand: false
      name: Delete HTTP Response Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 8ae6b224-d274-49e6-8665-43b78bdd5b6d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 850,
          "y": 770
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Events.ip
      value:
        complex:
          accessor: geoplugin_request
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: Coordinates.geoplugin_request
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: inputs.sourceip
          root: Coordinates
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value in context under the key you entered.
      id: 817a6f83-aad4-46a2-8035-4e4778523de7
      iscommand: false
      name: Set IP Address
      script: Set
      type: regular
      version: -1
    taskid: 817a6f83-aad4-46a2-8035-4e4778523de7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -230
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: Coordinates
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 1d06af95-318b-4397-8dbb-72b52f36f0a2
      iscommand: false
      name: Delete Coordinates Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 1d06af95-318b-4397-8dbb-72b52f36f0a2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 770
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: ImpossibleTraveler.Events
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Events.ip
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: inputs.sourceip
          root: Events
          transformers:
          - operator: StringToArray
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value in context under the key you entered.
      id: 4d690d07-5c35-42e4-8da1-3dfc737316f5
      iscommand: false
      name: Create Impossible Traveler Events
      script: Set
      type: regular
      version: -1
    taskid: 4d690d07-5c35-42e4-8da1-3dfc737316f5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -60
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: Events
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 7157a915-00e4-419b-8d9e-1e3b46bc706a
      iscommand: false
      name: Delete Events Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 7157a915-00e4-419b-8d9e-1e3b46bc706a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 770
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Events.Country
      value:
        complex:
          accessor: geoplugin_countryCode
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: Coordinates.geoplugin_request
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: inputs.sourceip
          root: Coordinates
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value in context under the key you entered.
      id: 97760e8c-ee4d-4656-8d19-65928cb54fcd
      iscommand: false
      name: Set Country
      script: Set
      type: regular
      version: -1
    taskid: 97760e8c-ee4d-4656-8d19-65928cb54fcd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": -230
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Events.identity_display_name
      value:
        complex:
          accessor: username
          root: alert
          transformers:
          - operator: FirstArrayElement
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value in context under the key you entered.
      id: 0411b244-1c46-466e-87f7-3f5770571e2f
      iscommand: false
      name: Set event identity
      script: Set
      type: regular
      version: -1
    taskid: 0411b244-1c46-466e-87f7-3f5770571e2f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1230,
          "y": -230
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
      - "23"
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ea2cf994-dcd6-4756-811f-6ac158487081
      iscommand: false
      name: Clear Processed Context
      type: title
      version: -1
    taskid: ea2cf994-dcd6-4756-811f-6ac158487081
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 630
        }
      }
  "28":
    continueonerror: true
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        complex:
          root: inputs.sourceip
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Retrieve the IP address verdict using the enabled integrations.
      id: ace7b867-75f1-48b0-8a9b-464fdb91d6d2
      iscommand: true
      name: Get IP address verdict
      script: '|||ip'
      type: regular
      version: -1
    taskid: ace7b867-75f1-48b0-8a9b-464fdb91d6d2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -730
        }
      }
  "29":
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    scriptarguments:
      Domain:
        complex:
          root: inputs.domain
      Username:
        complex:
          root: inputs.username
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Enrich accounts using one or more integrations.
        Supported integrations:
        - Active Directory
        - SailPoint IdentityNow
        - SailPoint IdentityIQ
        - PingOne
        - Okta
        - AWS IAM

        Also, the playbook supports the generic command 'iam-get-user' (implemented in IAM integrations. For more information, visit https://xsoar.pan.dev/docs/integrations/iam-integrations.
      id: 2eb086b8-6cf1-44f4-830f-a1ff14796a85
      iscommand: false
      name: Account Enrichment - Generic v2.1
      playbookId: Account Enrichment - Generic v2.1
      type: playbook
      version: -1
    taskid: 2eb086b8-6cf1-44f4-830f-a1ff14796a85
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 110,
          "y": 290
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_27_#default#": 0.49
    },
    "paper": {
      "dimensions": {
        "height": 1870,
        "width": 1950,
        "x": -340,
        "y": -865
      }
    }
  }
