contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.6.33
    packID: CortexAttackSurfaceManagement
    packName: Cortex Attack Surface Management
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Given the IP address this playbook enriches information from Qualys assets.
id: Cortex ASM - Qualys Enrichment
inputs:
- description: Remote IP in alert.
  key: QualysIP
  playbookInputQuery: null
  required: true
  value:
    complex:
      accessor: remoteip
      root: alert
      transformers:
      - operator: uniq
name: Cortex ASM - Qualys Enrichment
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e80bdae0-ec8d-496d-8d62-04ef23296a11
      iscommand: false
      name: ""
      version: -1
    taskid: e80bdae0-ec8d-496d-8d62-04ef23296a11
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -20
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: QualysV2
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.QualysIP
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "19"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines if the "Qualys" integration instance is enabled in order
        to find assets and asset tags.
      id: 43e1f342-cbfb-48a1-8ad9-5774b367d617
      iscommand: false
      name: Is Qualys enabled and input value defined?
      type: condition
      version: -1
    taskid: 43e1f342-cbfb-48a1-8ad9-5774b367d617
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 130
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a1948e2c-48d5-4140-8b3e-da1ccbd3b278
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a1948e2c-48d5-4140-8b3e-da1ccbd3b278
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -70,
          "y": 1860
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      details:
        simple: All
      ips:
        complex:
          root: inputs.QualysIP
      show_cloud_tags:
        simple: "1"
      show_tags:
        simple: "1"
    separatecontext: false
    skipunavailable: false
    task:
      brand: QualysV2
      description: View host information in the Qualys account.
      id: 2f6287f3-ccdb-46b8-8b16-1a78b2c2a1ea
      iscommand: true
      name: Lookup host information in Qualys
      script: QualysV2|||qualys-host-list
      type: regular
      version: -1
    taskid: 2f6287f3-ccdb-46b8-8b16-1a78b2c2a1ea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c45fa3d4-5a48-4943-8427-5bfb9e5a86aa
      iscommand: false
      name: Service Owner
      type: title
      version: -1
    taskid: c45fa3d4-5a48-4943-8427-5bfb9e5a86aa
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 250,
          "y": 1060
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
      - "7"
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bfcadac5-14c3-4fcb-8046-d1ef259d02b4
      iscommand: false
      name: Set Field
      type: title
      version: -1
    taskid: bfcadac5-14c3-4fcb-8046-d1ef259d02b4
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 895
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: afef85e5-4b2f-4648-8e10-6e37bb43f8a6
      iscommand: false
      name: System IDs
      type: title
      version: -1
    taskid: afef85e5-4b2f-4648-8e10-6e37bb43f8a6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 690,
          "y": 1060
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f9abd219-bdc1-47fa-8653-5b232d71d132
      iscommand: false
      name: Tags
      type: title
      version: -1
    taskid: f9abd219-bdc1-47fa-8653-5b232d71d132
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1060
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Endpoint
                root: Qualys
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "19"
      "yes":
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the last command returned Qualys asset information
        or not.
      id: a1170b57-070d-4b7f-8294-34525b9302c8
      iscommand: false
      name: Was a host found?
      type: condition
      version: -1
    taskid: a1170b57-070d-4b7f-8294-34525b9302c8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 530
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: OWNER
                root: Qualys.Endpoint
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the last command has owner or not.
      id: effc615e-cfd8-404f-8245-02889c184aed
      iscommand: false
      name: Was an owner found?
      type: condition
      version: -1
    taskid: effc615e-cfd8-404f-8245-02889c184aed
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 250,
          "y": 1210
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      gridfield:
        simple: asmserviceowner
      keys:
        simple: name,email,source,timestamp
      val1:
        complex:
          accessor: OWNER
          root: Qualys.Endpoint
          transformers:
          - operator: uniq
      val2:
        simple: n/a
      val3:
        simple: Qualys
      val4:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: TimeStampToDate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      id: 8c08c8d4-b81d-4ad0-8a98-ba8cd49fd6a2
      iscommand: false
      name: Set service owner grid field
      script: GridFieldSetup
      type: regular
      version: -1
    taskid: 8c08c8d4-b81d-4ad0-8a98-ba8cd49fd6a2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 250,
          "y": 1590
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 92580fd5-c665-4372-8e7d-a3719d4c0cfc
      iscommand: false
      name: Get current time
      script: GetTime
      type: regular
      version: -1
    taskid: 92580fd5-c665-4372-8e7d-a3719d4c0cfc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 250,
          "y": 1430
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      gridfield:
        simple: asmtags
      keys:
        simple: key,value,source
      val1:
        complex:
          accessor: TAG
          root: Qualys.Endpoint.TAGS
          transformers:
          - args:
              field:
                value:
                  simple: NAME
            operator: getField
          - operator: uniq
      val2:
        complex:
          accessor: TAG
          root: Qualys.Endpoint.TAGS
          transformers:
          - args:
              field:
                value:
                  simple: TAG_ID
            operator: getField
          - operator: uniq
      val3:
        simple: Qualys
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      id: c937921f-f1a3-407b-8d33-ef76e5535891
      iscommand: false
      name: Set tags grid field
      script: GridFieldSetup
      type: regular
      version: -1
    taskid: c937921f-f1a3-407b-8d33-ef76e5535891
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1590
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: TAGS
                root: Qualys.Endpoint
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the last command returned Qualys host with one or
        more tags.
      id: 92a44e95-df4a-4187-8d84-95d5de685f07
      iscommand: false
      name: Was a tag present?
      type: condition
      version: -1
    taskid: 92a44e95-df4a-4187-8d84-95d5de685f07
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1210
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      gridfield:
        simple: asmsystemids
      keys:
        simple: type,id,link
      val1:
        simple: QUALYS-ASSET-ID
      val2:
        complex:
          accessor: ID
          root: Qualys.Endpoint
      val3:
        simple: n/a
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      id: 76328686-392e-45d6-870f-d1c194bd729e
      iscommand: false
      name: Set system IDs grid field (asset ID)
      script: GridFieldSetup
      type: regular
      version: -1
    taskid: 76328686-392e-45d6-870f-d1c194bd729e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690,
          "y": 1360
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      gridfield:
        simple: asmenrichmentstatus
      keys:
        simple: source,record_exists,timestamp
      val1:
        simple: Qualys
      val2:
        simple: "true"
      val3:
        simple: TIMESTAMP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Instead of a value you can enter `TIMESTAMP` to get the current timestamp in ISO format. For example:
        `!GridFieldSetup keys=ip,src,timestamp val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" val3="TIMESTAMP" gridfiled="gridfield"`
      id: fdd708fa-95c4-4e32-8486-8ce116ce7b60
      iscommand: false
      name: Set ASM enrichment status to true
      script: GridFieldSetup
      type: regular
      version: -1
    taskid: fdd708fa-95c4-4e32-8486-8ce116ce7b60
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 730
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      gridfield:
        simple: asmenrichmentstatus
      keys:
        simple: source,record_exists,timestamp
      val1:
        simple: Qualys
      val2:
        simple: "false"
      val3:
        simple: TIMESTAMP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well.  Instead of a value you can enter `TIMESTAMP` to get the current timestamp in ISO format. For example:
        `!GridFieldSetup keys=ip,src,timestamp val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" val3="TIMESTAMP" gridfiled="gridfield"`
      id: 7f98677d-e83f-4e22-8e75-086d07b4c5ff
      iscommand: false
      name: Set ASM enrichment status to false
      script: GridFieldSetup
      type: regular
      version: -1
    taskid: 7f98677d-e83f-4e22-8e75-086d07b4c5ff
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -70,
          "y": 730
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_2_#default#": 0.36,
      "9_17_yes": 0.47
    },
    "paper": {
      "dimensions": {
        "height": 1945,
        "width": 1560,
        "x": -70,
        "y": -20
      }
    }
  }
