contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.9.0
    itemVersion: 1.7.29
    packID: CortexAttackSurfaceManagement
    packName: Cortex Attack Surface Management
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook is used to create Jira tickets directed toward service
  owners to notify them of their internet exposures.
id: Cortex ASM - Jira Notification
inputs:
- description: Body of the notification (email or ticket) sent to the potential service
    owner.
  key: OwnerNotificationBody
  playbookInputQuery: null
  required: true
  value: {}
- description: The Jira project key to associate with the issue.
  key: JiraProjectKey
  playbookInputQuery: null
  required: false
  value: {}
- description: Remediation Guidance of the Attack Surface Rule.
  key: RemediationGuidance
  playbookInputQuery: null
  required: true
  value: {}
name: Cortex ASM - Jira Notification
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: af645ade-de93-4220-8b4d-2fd0f93b0fe3
      iscommand: false
      name: ""
      version: -1
    taskid: af645ade-de93-4220-8b4d-2fd0f93b0fe3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -260
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      gridfield:
        simple: asmnotification
      keys:
        simple: type,value,url,timestamp
      val1:
        simple: Jira
      val2:
        complex:
          accessor: Key
          root: Ticket
      val3:
        complex:
          accessor: Key
          root: Ticket
          transformers:
          - operator: FirstArrayElement
          - args:
              prefix:
                value:
                  simple: browse/
              suffix: {}
            operator: concat
          - args:
              prefix:
                iscontext: true
                value:
                  simple: JiraDomain.url
              suffix:
                iscontext: true
            operator: concat
      val4:
        simple: TIMESTAMP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: |-
        Automation used to more easily populate a grid field. This is necessary when you want to assign certain values as static or if you have context paths that you will assign to different values as well. For example:
        `!GridFieldSetup keys=ip,src val1=${AWS.EC2.Instances.NetworkInterfaces.PrivateIpAddress} val2="AWS" gridfiled="gridfield"`
      id: 439be49e-ef74-43c7-85f5-116775b1f5d4
      iscommand: false
      name: Set notification grid field
      script: GridFieldSetup
      type: regular
      version: -1
    taskid: 439be49e-ef74-43c7-85f5-116775b1f5d4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a05fbee9-f55d-4f40-8de4-7e703f0607d9
      iscommand: false
      name: Complete
      type: title
      version: -1
    taskid: a05fbee9-f55d-4f40-8de4-7e703f0607d9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 580
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      description:
        complex:
          root: inputs.OwnerNotificationBody
          transformers:
          - args:
              prefix: {}
              suffix:
                iscontext: true
                value:
                  simple: inputs.RemediationGuidance
            operator: concat
          - args:
              limit: {}
              replaceWith: {}
              toReplace:
                value:
                  simple: <br>
            operator: replace
      extend-context:
        simple: 'JiraDomain=.={"url": val.self.split(''rest/api'')[0]}'
      issueTypeName:
        simple: Task
      priority:
        complex:
          accessor: severity
          root: alert
          transformers:
          - args:
              input_values:
                value:
                  simple: 1,2,3,4
              mapped_values:
                value:
                  simple: Low,Medium,High,Critical
            operator: MapValuesTransformer
      project_key:
        simple: ${inputs.JiraProjectKey}${Please insert Jira Project Key.Answers.0}
      projectKey:
        simple: ${inputs.JiraProjectKey}${Please insert Jira Project Key.Answers.0}
      summary:
        complex:
          accessor: name
          root: alert
          transformers:
          - args:
              prefix:
                value:
                  simple: 'Cortex ASM Alert: '
              suffix: {}
            operator: concat
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Creates a new issue in Jira.
      id: b199902c-b7a6-442f-8d29-68e778079712
      iscommand: true
      name: Create Jira ticket
      script: '|||jira-create-issue'
      type: regular
      version: -1
    taskid: b199902c-b7a6-442f-8d29-68e778079712
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.JiraProjectKey
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines if a Jira project key has been provided or not.
      id: 7a4f2026-ef32-4866-844b-65c8e7a64c07
      iscommand: false
      name: Is Jira project key set?
      type: condition
      version: -1
    taskid: 7a4f2026-ef32-4866-844b-65c8e7a64c07
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": -120
        }
      }
  "8":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: 'Please type in Jira project key:'
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: Add a single Jira project key that the Jira ticket will be created
          in.
        type: shortText
      sender: Your SOC team
      title: Please insert Jira Project Key
      totalanswers: 0
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Select owners to notify
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines who to send notification emails to based on analyst
        input.
      id: 8310b832-eff8-4d36-8256-fd00a8aad548
      iscommand: false
      name: Provide Jira project key
      type: collection
      version: -1
    taskid: 8310b832-eff8-4d36-8256-fd00a8aad548
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 700,
          "y": 60
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 905,
        "width": 630,
        "x": 450,
        "y": -260
      }
    }
  }
