contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    itemVersion: 2.6.15
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  ## Containment Plan - Disable Account

  This playbook is a sub-playbook within the containment plan playbook.
  The playbook disables users by utilizing the sub-playbook "Block Account - Generic v2"
id: Containment Plan - Disable Account
inputs:
- description: Set to 'True' to disable the user account.
  key: UserContainment
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
- description: The username to disable.
  key: Username
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Possible values:True/False. Default:True.
    Specify if User Verification is required to disable users.
  key: UserVerification
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
name: Containment Plan - Disable Account
outputs:
- contextPath: Blocklist.Final
  description: Blocked accounts
  type: unknown
quiet: true
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9fb1ed1d-c22c-48bb-8a3c-4d58bbca6347
      iscommand: false
      name: ""
      version: -1
    taskid: 9fb1ed1d-c22c-48bb-8a3c-4d58bbca6347
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -140
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4d874c50-7a1f-489c-8397-3fc3304eeea6
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 4d874c50-7a1f-489c-8397-3fc3304eeea6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 750
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: UsersBlockList
      value:
        complex:
          accessor: Final
          root: Blocklist
    separatecontext: false
    skipunavailable: true
    task:
      brand: Builtin
      description: commands.local.cmd.set.parent.alert.context
      id: 73bc4723-d270-4e04-8a74-c13b5b1369f1
      iscommand: true
      name: Set disabled users to the Alert context
      script: Builtin|||setParentIncidentContext
      type: regular
      version: -1
    taskid: 73bc4723-d270-4e04-8a74-c13b5b1369f1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 575
        }
      }
  "12":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.UserContainment
          operator: isEqualString
          right:
            value:
              simple: "True"
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Username
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Whether to disable the account based on the input values.
      id: 073f607c-a924-43c1-8852-d480e1454fdc
      iscommand: false
      name: Should disable the account?
      type: condition
      version: -1
    taskid: 073f607c-a924-43c1-8852-d480e1454fdc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 0
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: UsersToDisable
      value:
        complex:
          root: inputs.Username
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.11/Cortex-XSOAR-Administrator-Guide/Automations
      id: 32ec3207-df33-4d5f-8551-2a49ca677b62
      iscommand: false
      name: Set users to disable
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 32ec3207-df33-4d5f-8551-2a49ca677b62
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      Tag:
        simple: XSIAM alert - ${alert.id}
      UserVerification:
        complex:
          root: inputs.UserVerification
      Username:
        complex:
          root: UsersToDisable
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: b35ee9bb-51f1-4f64-8df5-b490d1592b2c
      iscommand: false
      name: Block Account - Generic v2
      playbookId: Block Account - Generic v2
      type: playbook
      version: -1
    taskid: b35ee9bb-51f1-4f64-8df5-b490d1592b2c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "12_2_#default#": 0.16
    },
    "paper": {
      "dimensions": {
        "height": 955,
        "width": 380,
        "x": 450,
        "y": -140
      }
    }
  }
