contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 628b5150-c57b-48bb-800c-a42ee0d8d6cf
inputs: []
name: saar2
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bdc2f7ec-2b94-4196-891f-ffc8bc7e3eae
      iscommand: false
      name: ""
      version: -1
    taskid: bdc2f7ec-2b94-4196-891f-ffc8bc7e3eae
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: gfgf
      id: 0b736bb6-a6a7-4486-8e2f-4299f37f842d
      iscommand: false
      name: saar5
      script: 55614b5e-85cb-45c2-8044-ba0902b19f77
      type: regular
      version: -1
    taskid: 0b736bb6-a6a7-4486-8e2f-4299f37f842d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
