contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: fd22050a-3fe6-4d28-8219-557fe284ea54
inputs: []
name: saar5
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7855fdde-7709-49de-8fed-5481bc7704ef
      iscommand: false
      name: ""
      version: -1
    taskid: 7855fdde-7709-49de-8fed-5481bc7704ef
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: dsd
      id: 64457f25-bb1b-40d5-8788-262c4dafec61
      iscommand: false
      name: saar
      script: a25d3ec7-2b44-4b4b-88ec-d162326d8a52
      type: regular
      version: -1
    taskid: 64457f25-bb1b-40d5-8788-262c4dafec61
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
