contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 26b8bd73-cf2b-4abb-80f9-b4b26b85adf6
inputs: []
name: pbtest
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a1c8d1e9-10eb-4b54-8e27-a9bcad7296a7
      iscommand: false
      name: ""
      version: -1
    taskid: a1c8d1e9-10eb-4b54-8e27-a9bcad7296a7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6fc34719-c04d-4c7e-8e29-02ed226b29ef
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 6fc34719-c04d-4c7e-8e29-02ed226b29ef
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 310
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 355,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
