contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 64b38b12-8d81-49e0-877b-39dd149596bf
inputs: []
name: new-version-test
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6ab2818a-5fae-4171-8443-e398562085be
      iscommand: false
      name: ""
      version: -1
    taskid: 6ab2818a-5fae-4171-8443-e398562085be
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cc108c5d-88f2-4882-8b8c-5b4598de390e
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: cc108c5d-88f2-4882-8b8c-5b4598de390e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 440
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e6b7213c-df5a-4c5a-82b2-03d6f43f3883
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: e6b7213c-df5a-4c5a-82b2-03d6f43f3883
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 770
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 815,
        "width": 390,
        "x": 440,
        "y": 50
      }
    }
  }
