contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.3.5
    packID: Pcysys
    packName: Pentera
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook will run a pentera task given the Pentera task name. It
  will generate the full action report that contains all the actions that Pentera
  made during the scan, and will create incidents according to the filters in the
  Pentera Filter and Create incidents playbook.
id: Pentera Run Scan and Create Incidents
inputs:
- description: The name of the Pentera task to run.
  key: PenteraTaskName
  playbookInputQuery: null
  required: true
  value: {}
name: Pentera Run Scan and Create Incidents
outputs: []
sourceplaybookid: Pentera Run Scan - Test
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0f3c125c-0340-40ad-8ae1-b487469ec90d
      iscommand: false
      name: ""
      version: -1
    taskid: 0f3c125c-0340-40ad-8ae1-b487469ec90d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      PenteraTaskName:
        simple: ${inputs.PenteraTaskName}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b6928fad-433c-4c03-80cd-59a4452c75df
      iscommand: false
      name: Pentera Run Scan
      playbookId: Pentera Run Scan
      type: playbook
      version: -1
    taskid: b6928fad-433c-4c03-80cd-59a4452c75df
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      Filter BlueKeep vulnerability:
        simple: "True"
      Filter MS17-010 vulnerability:
        simple: "True"
      Filter Minimum Severity:
        simple: "0"
      Filter network device default password usage:
        simple: "True"
      'Filter open shares ':
        simple: "True"
      Filter password cracking:
        simple: "True"
      FullActionReport:
        complex:
          accessor: TaskRun.FullActionReport
          root: Pentera
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sub-playbook to select specific entries from the Pentera action
        report and create incidents for each of the selected entries
      id: 350ca2f1-abec-4bf2-884a-61b7c021777d
      iscommand: false
      name: Pentera Filter And Create Incident
      playbookId: Pentera Filter And Create Incident
      type: playbook
      version: -1
    taskid: 350ca2f1-abec-4bf2-884a-61b7c021777d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: db084004-95a6-4fc7-8db9-bf4b2f3dbe94
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: db084004-95a6-4fc7-8db9-bf4b2f3dbe94
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
