contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d33bbf3d-6c79-4174-82f1-89058b91e739
inputs: []
name: pbtest
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6d4ef5ae-cdd0-4a1d-808a-b34b95c48bb7
      iscommand: false
      name: ""
      version: -1
    taskid: 6d4ef5ae-cdd0-4a1d-808a-b34b95c48bb7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 778bf2d0-72eb-4828-8945-048a1c850353
      iscommand: false
      name: adsaas
      type: regular
      version: -1
    taskid: 778bf2d0-72eb-4828-8945-048a1c850353
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 430
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 295,
        "width": 380,
        "x": 450,
        "y": 230
      }
    }
  }
