contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 54c0fa18-2524-4859-8690-61ceb0aa150a
inputs: []
name: pbtest
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 24354a34-a5d1-4ffb-89e2-047f439f88c6
      iscommand: false
      name: ""
      version: -1
    taskid: 24354a34-a5d1-4ffb-89e2-047f439f88c6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3d3b9fa4-6775-4fb1-8260-3d03d269299a
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 3d3b9fa4-6775-4fb1-8260-3d03d269299a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 290
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 335,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
