contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 515ac114-806b-4741-8b25-010dd4fbc50a
inputs: []
name: saar2
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: de58bb06-6a83-4568-88be-53e68c632248
      iscommand: false
      name: ""
      version: -1
    taskid: de58bb06-6a83-4568-88be-53e68c632248
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: dsd
      id: 0b5d81d9-8c3b-45e2-8f98-d4c8c4756b55
      iscommand: false
      name: saar
      script: a25d3ec7-2b44-4b4b-88ec-d162326d8a52
      type: regular
      version: -1
    taskid: 0b5d81d9-8c3b-45e2-8f98-d4c8c4756b55
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
