id: 8eefa1e5-eee0-416d-8707-b76c6d940eb4
version: 0
name: Master
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: dfc953fb-aab5-48d0-8e94-0c08a9033022
    type: start
    task:
      id: dfc953fb-aab5-48d0-8e94-0c08a9033022
      version: -1
      name: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
