contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 23cbb0ed-38d7-4a7f-8cbd-06cb2d93c65e
inputs: []
name: empty-commit
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 513f24ed-474a-4092-8c02-3f0aae4c4d5a
      iscommand: false
      name: ""
      version: -1
    taskid: 513f24ed-474a-4092-8c02-3f0aae4c4d5a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e883551f-d755-4842-8b10-685ece1cbe4e
      iscommand: false
      name: Untitled Taskffg
      type: regular
      version: -1
    taskid: e883551f-d755-4842-8b10-685ece1cbe4e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 420,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 445,
        "width": 410,
        "x": 420,
        "y": 50
      }
    }
  }
