contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f9c86997-02a9-4d60-8e52-a2cef09bad9x
inputs: []
name: gni
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 03cead7f-4af1-4fc3-8292-fe03358062d9
      iscommand: false
      name: ""
      version: -1
    taskid: 03cead7f-4af1-4fc3-8292-fe03358062d9
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 097fa458-ff29-40c2-84a3-4aaac8255475
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 097fa458-ff29-40c2-84a3-4aaac8255475
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 170
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 215,
        "width": 390,
        "x": 450,
        "y": 50
      }
    }
  }
