contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 0d30701a-8ca2-4865-8bff-02f9e9b55a9d
inputs: []
name: exclude -test
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ddc71e38-e7ba-4be6-846e-b2e5ee26f900
      iscommand: false
      name: ""
      version: -1
    taskid: ddc71e38-e7ba-4be6-846e-b2e5ee26f900
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: afc9e21e-2dda-40f7-875c-e45f7bc2dc23
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: afc9e21e-2dda-40f7-875c-e45f7bc2dc23
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 330
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 375,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
