contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: efdfba50-3d5f-4a69-88cb-a342ac0b703d
inputs: []
name: 6test
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1a652cf4-0d67-4592-8b6e-07c14bbaf9ae
      iscommand: false
      name: ""
      version: -1
    taskid: 1a652cf4-0d67-4592-8b6e-07c14bbaf9ae
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1a16ba30-01cb-44aa-8452-a17796bdba68
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 1a16ba30-01cb-44aa-8452-a17796bdba68
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 260
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 46d25bbe-e414-4ed5-8a23-68ee05b8cc79
      iscommand: false
      name: dgfdfdfdfUntitled Task
      type: regular
      version: -1
    taskid: 46d25bbe-e414-4ed5-8a23-68ee05b8cc79
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 420,
          "y": 520
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 10707a56-2607-4daf-8e94-afe8a2153aca
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 10707a56-2607-4daf-8e94-afe8a2153aca
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 430,
          "y": 770
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 815,
        "width": 410,
        "x": 420,
        "y": 50
      }
    }
  }
