contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 220c4e5b-1888-412f-824c-3a0a7a83f3ec
inputs: []
name: amir-test-send mail
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 652aef84-aca9-49e8-8c6f-b4ac22885615
      iscommand: false
      name: ""
      version: -1
    taskid: 652aef84-aca9-49e8-8c6f-b4ac22885615
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: 'starting test - amir - tombstone '
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: db17473a-aeb5-492e-8c66-18ec10afb428
      iscommand: false
      name: 'print - start test '
      script: Print
      type: regular
      version: -1
    taskid: db17473a-aeb5-492e-8c66-18ec10afb428
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 250
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: amir the big
      subject:
        simple: amir the big
      to:
        simple: amir876@gmail.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send an email
      id: 2df96fcf-c724-4075-8ccd-91dacf7c52e4
      iscommand: true
      name: send-mail
      script: '|||send-mail'
      type: regular
      version: -1
    taskid: 2df96fcf-c724-4075-8ccd-91dacf7c52e4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 470
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: done
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: d86aaef2-2306-4b87-8d91-d6455cf2351d
      iscommand: false
      name: done
      script: Print
      type: regular
      version: -1
    taskid: d86aaef2-2306-4b87-8d91-d6455cf2351d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 700
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 745,
        "width": 390,
        "x": 440,
        "y": 50
      }
    }
  }
